version: '3.3'

services:

  tubearchivist:
    container_name: tubearchivist
    hostname: tubearchivist
    restart: unless-stopped
    build:
      context: ./src
      args:
        PROXY: "http://YOUR-PROXY-SERVER-ADDRESS:PORT" # Ex.: http://10.10.10.1:8080

    expose:
      - 8000

    volumes:
      - ./media:/youtube
      - ./cache:/cache

    links:
      - archivist-redis
      - archivist-es

    environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
      - REDIS_PORT=6379
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=tube.somehost.com           # set your host name
      - TA_USERNAME=TAUSER                  # your initial TA credentials
      - TA_PASSWORD=TAPASS123               # your initial TA credentials
      - ELASTIC_PASSWORD=ESPASS123          # set password for Elasticsearch
      - TZ=Europe/Paris                     # set your time zone

    depends_on:
      - archivist-es
      - archivist-redis

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s

    logging:
      driver: "json-file"
      options:
        max-size: "1m"

    network_mode: bridge

  archivist-redis:
    image: redis/redis-stack-server
    hostname: archivist-redis
    container_name: archivist-redis
    restart: unless-stopped

    expose:
      - 6379

    volumes:
      - ./redis:/data

    depends_on:
      - archivist-es

    logging:
      driver: "json-file"
      options:
        max-size: "1m"

    network_mode: bridge

  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.9.0
    container_name: archivist-es
    hostname: archivist-es
    restart: unless-stopped

    environment:
      - ELASTIC_PASSWORD=ESPASS123         # matching Elasticsearch password
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=true
      - discovery.type=single-node
      - path.repo=/usr/share/elasticsearch/data/snapshot

    ulimits:
      memlock:
        soft: -1
        hard: -1

    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme

    expose:
      - 9200

    logging:
      driver: "json-file"
      options:
        max-size: "1m"

    network_mode: bridge
